language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - docker pull openjdk:8-jre-alpine

script:
  - ./mvnw -s .mvn/wrapper/settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - ./mvnw -s .mvn/wrapper/settings.xml deploy jib:build -P deploy-docker
  - docker pull franckclerget/mindmap
  - docker tag franckclerget/mindmap registry.heroku.com/$HEROKU_APP_NAME/web

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script:
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: main
